//! Kernel golden fixtures.
//!
//! The userspace harness is the reference for translated fragment bytes. A
//! golden file captures one fixture's input text and the harness's encoded
//! `compile_request` output as plain Rust constants, so the kernel module can
//! `include!` it and compare its own in-kernel translation byte-for-byte.

use std::fmt::Write as _;

use crate::shared::trans::input::{TranslationRequest, TranslationTrigger};
use crate::shared::trans::translate::compile_request;
use crate::{encode_fragment, verify_encoded_fragment, MockCodeProvider};

pub struct GoldenInput<'a> {
    /// Fixture path as passed to `scripts/compile-asm-fixture.sh`.
    pub fixture: &'a str,
    pub hot_svc_symbol: &'a str,
    pub text_base: u64,
    pub entry_pc: u64,
    pub text_words: &'a [u32],
}

/// Runs the harness translation path and returns the encoded fragment, which must
/// pass the verifier: the module only ever gets bytes the verifier accepted.
fn harness_fragment_bytes(
    text_base: u64,
    entry_pc: u64,
    text_words: &[u32],
) -> Result<Vec<u8>, String> {
    let text_bytes: Vec<u8> = text_words
        .iter()
        .flat_map(|word| word.to_le_bytes())
        .collect();
    let code = MockCodeProvider::new(text_base, text_bytes);
    // `trigger` and `regs` do not influence `compile_request` output; the
    // kernel module builds the identical request.
    let request = TranslationRequest {
        entry_pc,
        trigger: TranslationTrigger::HotSvc,
        regs: None,
    };
    let fragment = compile_request(&request, &code).map_err(|err| err.to_string())?;
    let encoded = encode_fragment(&fragment)?;
    verify_encoded_fragment(&fragment, &encoded)
        .map_err(|err| format!("verifier rejected the golden fragment: {err:?}"))?;
    Ok(encoded)
}

/// Renders the golden Rust source for `input`.
pub fn render_golden(input: &GoldenInput<'_>) -> Result<String, String> {
    let fragment = harness_fragment_bytes(input.text_base, input.entry_pc, input.text_words)?;

    let mut out = String::new();
    writeln!(out, "// @generated by harness/src/bin/dump-golden.rs. Do not edit.").unwrap();
    writeln!(out, "// Regenerate with `make kernel-golden`.").unwrap();
    writeln!(out, "//").unwrap();
    writeln!(
        out,
        "// Reference output of the userspace harness (`compile_request` + `A64Insn::encode`)"
    )
    .unwrap();
    writeln!(
        out,
        "// for the hot SVC case of this fixture. The kernel module recompiles the same"
    )
    .unwrap();
    writeln!(out, "// input at init and must reproduce these bytes exactly.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub(crate) const GOLDEN_FIXTURE: &str = {:?};", input.fixture).unwrap();
    writeln!(
        out,
        "pub(crate) const GOLDEN_HOT_SVC_SYMBOL: &str = {:?};",
        input.hot_svc_symbol
    )
    .unwrap();
    writeln!(out, "pub(crate) const GOLDEN_TEXT_BASE: u64 = {:#x};", input.text_base).unwrap();
    writeln!(out, "pub(crate) const GOLDEN_ENTRY_PC: u64 = {:#x};", input.entry_pc).unwrap();
    writeln!(
        out,
        "pub(crate) const GOLDEN_TEXT_WORDS: [u32; {}] = [",
        input.text_words.len()
    )
    .unwrap();
    for chunk in input.text_words.chunks(6) {
        let line: Vec<String> = chunk.iter().map(|word| format!("{word:#010x},")).collect();
        writeln!(out, "    {}", line.join(" ")).unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(
        out,
        "pub(crate) const GOLDEN_FRAGMENT_BYTES: [u8; {}] = [",
        fragment.len()
    )
    .unwrap();
    for chunk in fragment.chunks(12) {
        let line: Vec<String> = chunk.iter().map(|byte| format!("{byte:#04x},")).collect();
        writeln!(out, "    {}", line.join(" ")).unwrap();
    }
    writeln!(out, "];").unwrap();
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    mod checked_in {
        include!("../../tests/arm64/golden/toy_cfg_hot_svc_mark.rs");
    }

    /// The checked-in kernel golden must equal what the harness produces today.
    /// If this fails, the translator output changed: inspect the diff, then run
    /// `make kernel-golden` and commit the regenerated file.
    #[test]
    fn kernel_golden_matches_harness_output() {
        let fragment = harness_fragment_bytes(
            checked_in::GOLDEN_TEXT_BASE,
            checked_in::GOLDEN_ENTRY_PC,
            &checked_in::GOLDEN_TEXT_WORDS,
        )
        .unwrap();
        assert_eq!(
            fragment.as_slice(),
            checked_in::GOLDEN_FRAGMENT_BYTES.as_slice(),
            "golden fragment bytes are stale; run `make kernel-golden`"
        );

        let rendered = render_golden(&GoldenInput {
            fixture: checked_in::GOLDEN_FIXTURE,
            hot_svc_symbol: checked_in::GOLDEN_HOT_SVC_SYMBOL,
            text_base: checked_in::GOLDEN_TEXT_BASE,
            entry_pc: checked_in::GOLDEN_ENTRY_PC,
            text_words: &checked_in::GOLDEN_TEXT_WORDS,
        })
        .unwrap();
        assert!(
            rendered == include_str!("../../tests/arm64/golden/toy_cfg_hot_svc_mark.rs"),
            "tests/arm64/golden/toy_cfg_hot_svc_mark.rs is stale; run `make kernel-golden`"
        );
    }
}
