use crate::model::{FieldSpec, InstructionSpec, OperandRoleSpec, VariantSpec};
use anyhow::{bail, Result};

#[derive(Clone, Debug)]
struct RenderField {
    name: String,
    width: u8,
    rust_name: String,
    rust_type: String,
    encode_lines: Vec<String>,
    decode_value: String,
    rewrite_value: String,
}

#[derive(Clone, Debug)]
struct MemGroup {
    base_field: String,
    offset_field: String,
    base_shift: u8,
    offset_width: u8,
    offset_shift: u8,
    mode: &'static str,
    offset_decode: String,
    base_decode: String,
}

#[derive(Clone, Debug)]
struct RenderVariant<'a> {
    spec: &'a VariantSpec,
    key: String,
    variant_name: String,
    fields: Vec<RenderField>,
    operand_array_name: String,
}

pub fn render_rust(specs: &[InstructionSpec]) -> Result<String> {
    let mut lines = vec![
        "// Generated by specgen from Arm ISA XML.".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug)]".to_string(),
        "pub struct GeneratedFieldSpec {".to_string(),
        "    pub name: &'static str,".to_string(),
        "    pub hi: u8,".to_string(),
        "    pub lo: u8,".to_string(),
        "    pub width: u8,".to_string(),
        "    pub mask: u32,".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "impl GeneratedFieldSpec {".to_string(),
        "    pub const fn shift(&self) -> u8 {".to_string(),
        "        self.lo".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn extract(&self, word: u32) -> u32 {".to_string(),
        "        (word & self.mask) >> self.lo".to_string(),
        "    }".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64RegWidth {".to_string(),
        "    W32,".to_string(),
        "    X64,".to_string(),
        "    Unknown,".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64Reg31Mode {".to_string(),
        "    Xzr,".to_string(),
        "    Sp,".to_string(),
        "    Forbidden,".to_string(),
        "    Unknown,".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub struct A64Reg {".to_string(),
        "    pub enc: u8,".to_string(),
        "    pub width: A64RegWidth,".to_string(),
        "    pub reg31: A64Reg31Mode,".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "impl A64Reg {".to_string(),
        "    pub const fn new(enc: u8, width: A64RegWidth, reg31: A64Reg31Mode) -> Self {"
            .to_string(),
        "        Self { enc, width, reg31 }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn x(enc: u8) -> Self {".to_string(),
        "        Self::new(enc, A64RegWidth::X64, A64Reg31Mode::Xzr)".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn w(enc: u8) -> Self {".to_string(),
        "        Self::new(enc, A64RegWidth::W32, A64Reg31Mode::Xzr)".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn x_sp(enc: u8) -> Self {".to_string(),
        "        Self::new(enc, A64RegWidth::X64, A64Reg31Mode::Sp)".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn w_sp(enc: u8) -> Self {".to_string(),
        "        Self::new(enc, A64RegWidth::W32, A64Reg31Mode::Sp)".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn unknown(enc: u8) -> Self {".to_string(),
        "        Self::new(enc, A64RegWidth::Unknown, A64Reg31Mode::Unknown)".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn enc(self) -> u8 {".to_string(),
        "        self.enc".to_string(),
        "    }".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub struct A64Imm {".to_string(),
        "    pub raw: u32,".to_string(),
        "    pub bits: u8,".to_string(),
        "    pub value: i64,".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "impl A64Imm {".to_string(),
        "    pub const fn new(raw: u32, bits: u8, value: i64) -> Self {".to_string(),
        "        Self { raw, bits, value }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn unsigned(raw: u32, bits: u8) -> Self {".to_string(),
        "        Self::new(raw, bits, raw as i64)".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn signed(raw: u32, bits: u8) -> Self {".to_string(),
        "        Self::new(raw, bits, sign_extend_a64(raw, bits))".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn scaled_unsigned(raw: u32, bits: u8, scale: u8) -> Self {".to_string(),
        "        Self::new(raw, bits, (raw as i64) << scale)".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn scaled_signed(raw: u32, bits: u8, scale: u8) -> Self {".to_string(),
        "        Self::new(raw, bits, sign_extend_a64(raw, bits) << scale)".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn raw(self) -> u32 {".to_string(),
        "        self.raw".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn value(self) -> i64 {".to_string(),
        "        self.value".to_string(),
        "    }".to_string(),
        "}".to_string(),
        "".to_string(),
        "const fn sign_extend_a64(value: u32, bits: u8) -> i64 {".to_string(),
        "    let shift = 64 - bits as u32;".to_string(),
        "    ((value as i64) << shift) >> shift".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64Mem {".to_string(),
        "    Offset { base: A64Reg, offset: A64Imm },".to_string(),
        "    PreIndex { base: A64Reg, offset: A64Imm },".to_string(),
        "    PostIndex { base: A64Reg, offset: A64Imm },".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "impl A64Mem {".to_string(),
        "    pub const fn offset(base: A64Reg, offset: A64Imm) -> Self {".to_string(),
        "        Self::Offset { base, offset }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn pre_index(base: A64Reg, offset: A64Imm) -> Self {".to_string(),
        "        Self::PreIndex { base, offset }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn post_index(base: A64Reg, offset: A64Imm) -> Self {".to_string(),
        "        Self::PostIndex { base, offset }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn base(self) -> A64Reg {".to_string(),
        "        match self {".to_string(),
        "            Self::Offset { base, .. } | Self::PreIndex { base, .. } | Self::PostIndex { base, .. } => base,".to_string(),
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn offset_imm(self) -> A64Imm {".to_string(),
        "        match self {".to_string(),
        "            Self::Offset { offset, .. } | Self::PreIndex { offset, .. } | Self::PostIndex { offset, .. } => offset,".to_string(),
        "        }".to_string(),
        "    }".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64OperandRole {".to_string(),
        "    RegRead { field: &'static str, width: A64RegWidth },".to_string(),
        "    RegWrite { field: &'static str, width: A64RegWidth },".to_string(),
        "    RegReadWrite { field: &'static str, width: A64RegWidth },".to_string(),
        "    ImplicitRegWrite { reg: u8, width: A64RegWidth },".to_string(),
        "    BranchTarget { field: &'static str, scale: u8, bits: u8 },".to_string(),
        "    MemBase { field: &'static str },".to_string(),
        "    MemOffset { field: &'static str },".to_string(),
        "    FlagsRead,".to_string(),
        "    FlagsWrite,".to_string(),
        "    ControlFlow,".to_string(),
        "    Memory,".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug)]".to_string(),
        "pub struct GeneratedInsnSpec {".to_string(),
        "    pub key: &'static str,".to_string(),
        "    pub mnemonic: &'static str,".to_string(),
        "    pub heading: &'static str,".to_string(),
        "    pub title: &'static str,".to_string(),
        "    pub encoding_label: &'static str,".to_string(),
        "    pub mask: u32,".to_string(),
        "    pub value: u32,".to_string(),
        "    pub fields: &'static [GeneratedFieldSpec],".to_string(),
        "    pub operands: &'static [A64OperandRole],".to_string(),
        "    pub asm: &'static str,".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "impl GeneratedInsnSpec {".to_string(),
        "    pub const fn matches(&self, word: u32) -> bool {".to_string(),
        "        (word & self.mask) == self.value".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn field(&self, name: &str) -> Option<&'static GeneratedFieldSpec> {".to_string(),
        "        let mut index = 0;".to_string(),
        "        while index < self.fields.len() {".to_string(),
        "            let field = &self.fields[index];".to_string(),
        "            if field.name == name {".to_string(),
        "                return Some(field);".to_string(),
        "            }".to_string(),
        "            index += 1;".to_string(),
        "        }".to_string(),
        "        None".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn extract_field(&self, word: u32, name: &str) -> Option<u32> {".to_string(),
        "        self.field(name).map(|field| field.extract(word))".to_string(),
        "    }".to_string(),
        "}".to_string(),
        "".to_string(),
    ];

    lines.extend(render_a64_insn(specs)?);
    render_tables(specs, &mut lines)?;
    Ok(lines.join("\n"))
}

fn render_a64_insn(specs: &[InstructionSpec]) -> Result<Vec<String>> {
    let variants = render_variants(specs);
    let mut lines = vec![
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64Insn {".to_string(),
    ];

    for variant in &variants {
        lines.push(format!("    {} {{", variant.variant_name));
        for field in &variant.fields {
            lines.push(format!("        {}: {},", field.rust_name, field.rust_type));
        }
        lines.push("    },".to_string());
    }
    lines.push("}".to_string());
    lines.push("".to_string());

    lines.extend([
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64EncodeError {".to_string(),
        "    FieldOutOfRange {".to_string(),
        "        insn: &'static str,".to_string(),
        "        field: &'static str,".to_string(),
        "        value: u32,".to_string(),
        "        width: u8,".to_string(),
        "    },".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64RewriteError {".to_string(),
        "    UnsupportedField {".to_string(),
        "        insn: &'static str,".to_string(),
        "        field: &'static str,".to_string(),
        "    },".to_string(),
        "    FieldOutOfRange {".to_string(),
        "        insn: &'static str,".to_string(),
        "        field: &'static str,".to_string(),
        "        value: u32,".to_string(),
        "        width: u8,".to_string(),
        "    },".to_string(),
        "}".to_string(),
        "".to_string(),
        "fn encode_a64_field(".to_string(),
        "    insn: &'static str,".to_string(),
        "    field: &'static str,".to_string(),
        "    value: u32,".to_string(),
        "    width: u8,".to_string(),
        "    shift: u8,".to_string(),
        ") -> Result<u32, A64EncodeError> {".to_string(),
        "    if width < 32 && value >= (1_u32 << width) {".to_string(),
        "        return Err(A64EncodeError::FieldOutOfRange {".to_string(),
        "            insn,".to_string(),
        "            field,".to_string(),
        "            value,".to_string(),
        "            width,".to_string(),
        "        });".to_string(),
        "    }".to_string(),
        "    Ok(value << shift)".to_string(),
        "}".to_string(),
        "".to_string(),
        "fn validate_a64_rewrite_field(".to_string(),
        "    insn: &'static str,".to_string(),
        "    field: &'static str,".to_string(),
        "    value: u32,".to_string(),
        "    width: u8,".to_string(),
        ") -> Result<(), A64RewriteError> {".to_string(),
        "    if width < 32 && value >= (1_u32 << width) {".to_string(),
        "        return Err(A64RewriteError::FieldOutOfRange {".to_string(),
        "            insn,".to_string(),
        "            field,".to_string(),
        "            value,".to_string(),
        "            width,".to_string(),
        "        });".to_string(),
        "    }".to_string(),
        "    Ok(())".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "impl A64Insn {".to_string(),
        "    pub const fn key(&self) -> &'static str {".to_string(),
        "        match self {".to_string(),
    ]);
    for variant in &variants {
        lines.push(format!(
            "            Self::{} {{ .. }} => \"{}\",",
            variant.variant_name, variant.key
        ));
    }

    lines.extend([
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn mnemonic(&self) -> &'static str {".to_string(),
        "        match self {".to_string(),
    ]);
    for variant in &variants {
        lines.push(format!(
            "            Self::{} {{ .. }} => \"{}\",",
            variant.variant_name, variant.spec.mnemonic
        ));
    }

    lines.extend([
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn asm_template(&self) -> &'static str {".to_string(),
        "        match self {".to_string(),
    ]);
    for variant in &variants {
        lines.push(format!(
            "            Self::{} {{ .. }} => {},",
            variant.variant_name,
            rust_string(&variant.spec.asm)
        ));
    }

    lines.extend([
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn decode(word: u32) -> Option<Self> {".to_string(),
        "        decode_a64_insn(word)".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn encode(self) -> Result<u32, A64EncodeError> {".to_string(),
        "        match self {".to_string(),
    ]);
    render_encode_arms(&variants, &mut lines);

    lines.extend([
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn branch_target_imm(&self, field: &'static str) -> Option<u32> {".to_string(),
        "        match self {".to_string(),
    ]);
    render_branch_getter_arms(&variants, &mut lines)?;

    lines.extend([
        "            _ => None,".to_string(),
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn set_branch_target_imm(".to_string(),
        "        self,".to_string(),
        "        field: &'static str,".to_string(),
        "        encoded: u32,".to_string(),
        "    ) -> Result<Self, A64RewriteError> {".to_string(),
        "        let insn_key = self.key();".to_string(),
        "        match self {".to_string(),
    ]);
    render_branch_setter_arms(&variants, &mut lines)?;

    lines.extend([
        "            _ => Err(A64RewriteError::UnsupportedField {".to_string(),
        "                insn: insn_key,".to_string(),
        "                field,".to_string(),
        "            }),".to_string(),
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn operand_roles(&self) -> &'static [A64OperandRole] {".to_string(),
        "        match self {".to_string(),
    ]);
    for variant in &variants {
        lines.push(format!(
            "            Self::{} {{ .. }} => {},",
            variant.variant_name, variant.operand_array_name
        ));
    }

    lines.extend([
        "        }".to_string(),
        "    }".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "pub fn decode_a64_insn(word: u32) -> Option<A64Insn> {".to_string(),
    ]);
    render_decode_arms(&variants, &mut lines);

    lines.extend(["    None".to_string(), "}".to_string(), "".to_string()]);
    Ok(lines)
}

fn render_variants(specs: &[InstructionSpec]) -> Vec<RenderVariant<'_>> {
    specs
        .iter()
        .flat_map(|spec| &spec.variants)
        .map(|variant| {
            let key = format!("{}.{}", variant.section_id, variant.encoding_name);
            let mem_group = memory_group(variant);
            let fields = variant
                .fields
                .iter()
                .filter(|field| field.variable)
                .filter(|field| {
                    mem_group.as_ref().is_none_or(|mem| {
                        field.name != mem.base_field && field.name != mem.offset_field
                    })
                })
                .map(|field| render_field(variant, field))
                .chain(mem_group.as_ref().map(render_mem_field))
                .collect();
            RenderVariant {
                spec: variant,
                variant_name: rust_variant_ident(&key),
                operand_array_name: format!("OPERANDS_{}", rust_ident(&key)),
                key,
                fields,
            }
        })
        .collect()
}

fn render_field(variant: &VariantSpec, field: &FieldSpec) -> RenderField {
    let rust_name = rust_field_ident(&field.name);
    if is_register_field(field) {
        let width = register_width(variant, &field.name);
        let reg31 = register_31_mode(variant, &field.name);
        let raw_value = format!("((word & {}) >> {}) as u8", field.mask, field.shift);
        return RenderField {
            name: field.name.clone(),
            width: field.width,
            rust_name: rust_name.clone(),
            rust_type: "A64Reg".to_string(),
            encode_lines: vec![format!(
                "word |= encode_a64_field(\"{{key}}\", \"{}\", {}.enc() as u32, {}, {})?;",
                field.name, rust_name, field.width, field.shift
            )],
            decode_value: format!("A64Reg::new({raw_value}, {width}, {reg31})"),
            rewrite_value: format!("A64Reg::new(encoded as u8, {width}, {reg31})"),
        };
    }

    if field.name.starts_with("imm") {
        let raw_value = format!("((word & {}) >> {}) as u32", field.mask, field.shift);
        let decode_value = render_imm_decode(variant, field, &raw_value);
        return RenderField {
            name: field.name.clone(),
            width: field.width,
            rust_name: rust_name.clone(),
            rust_type: "A64Imm".to_string(),
            encode_lines: vec![format!(
                "word |= encode_a64_field(\"{{key}}\", \"{}\", {}.raw(), {}, {})?;",
                field.name, rust_name, field.width, field.shift
            )],
            decode_value,
            rewrite_value: render_imm_decode(variant, field, "encoded"),
        };
    }

    RenderField {
        name: field.name.clone(),
        width: field.width,
        rust_name: rust_name.clone(),
        rust_type: rust_field_type(field.width).to_string(),
        encode_lines: vec![format!(
            "word |= encode_a64_field(\"{{key}}\", \"{}\", {} as u32, {}, {})?;",
            field.name, rust_name, field.width, field.shift
        )],
        decode_value: format!(
            "((word & {}) >> {}) as {}",
            field.mask,
            field.shift,
            rust_field_type(field.width)
        ),
        rewrite_value: format!("encoded as {}", rust_field_type(field.width)),
    }
}

fn render_mem_field(mem: &MemGroup) -> RenderField {
    RenderField {
        name: "mem".to_string(),
        width: 0,
        rust_name: "mem".to_string(),
        rust_type: "A64Mem".to_string(),
        encode_lines: vec![
            format!(
                "word |= encode_a64_field(\"{{key}}\", \"{}\", mem.base().enc() as u32, 5, {})?;",
                mem.base_field, mem.base_shift
            ),
            format!(
                "word |= encode_a64_field(\"{{key}}\", \"{}\", mem.offset_imm().raw(), {}, {})?;",
                mem.offset_field, mem.offset_width, mem.offset_shift
            ),
        ],
        decode_value: format!(
            "A64Mem::{}({}, {})",
            mem.mode, mem.base_decode, mem.offset_decode
        ),
        rewrite_value: "mem".to_string(),
    }
}

fn render_encode_arms(variants: &[RenderVariant<'_>], lines: &mut Vec<String>) {
    for variant in variants {
        if variant.fields.is_empty() {
            lines.push(format!(
                "            Self::{} {{ }} => {{",
                variant.variant_name
            ));
            lines.push(format!(
                "                let word = {};",
                variant.spec.value
            ));
        } else {
            let field_list = variant
                .fields
                .iter()
                .map(|field| field.rust_name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            lines.push(format!(
                "            Self::{} {{ {} }} => {{",
                variant.variant_name, field_list
            ));
            lines.push(format!(
                "                let mut word = {};",
                variant.spec.value
            ));
        }

        for field in &variant.fields {
            for line in &field.encode_lines {
                lines.push(format!(
                    "                {}",
                    line.replace("{key}", &variant.key)
                ));
            }
        }
        lines.push("                Ok(word)".to_string());
        lines.push("            }".to_string());
    }
}

fn render_decode_arms(variants: &[RenderVariant<'_>], lines: &mut Vec<String>) {
    for variant in variants {
        lines.push(format!(
            "    if (word & {}) == {} {{",
            variant.spec.mask, variant.spec.value
        ));
        if variant.fields.is_empty() {
            lines.push(format!(
                "        return Some(A64Insn::{} {{ }});",
                variant.variant_name
            ));
        } else {
            lines.push(format!(
                "        return Some(A64Insn::{} {{",
                variant.variant_name
            ));
            for field in &variant.fields {
                lines.push(format!(
                    "            {}: {},",
                    field.rust_name, field.decode_value
                ));
            }
            lines.push("        });".to_string());
        }
        lines.push("    }".to_string());
    }
}

fn render_branch_getter_arms(
    variants: &[RenderVariant<'_>],
    lines: &mut Vec<String>,
) -> Result<()> {
    for variant in variants {
        for role in branch_target_roles(variant.spec) {
            let target_field = field_by_name(&variant.fields, &role.field)?;
            lines.push(format!(
                "            Self::{} {{ {}, .. }} if field == \"{}\" => Some({}),",
                variant.variant_name,
                target_field.rust_name,
                target_field.name,
                field_raw_expr(target_field)
            ));
        }
    }
    Ok(())
}

fn render_branch_setter_arms(
    variants: &[RenderVariant<'_>],
    lines: &mut Vec<String>,
) -> Result<()> {
    for variant in variants {
        for role in branch_target_roles(variant.spec) {
            let target_field = field_by_name(&variant.fields, &role.field)?;
            let mut pattern_fields = Vec::new();
            let mut result_fields = Vec::new();

            for field in &variant.fields {
                if field.name == target_field.name {
                    result_fields.push(format!("{}: {}", field.rust_name, field.rewrite_value));
                } else {
                    pattern_fields.push(field.rust_name.clone());
                    result_fields.push(field.rust_name.clone());
                }
            }

            let pattern = if pattern_fields.is_empty() {
                "..".to_string()
            } else {
                format!("{}, ..", pattern_fields.join(", "))
            };
            lines.push(format!(
                "            Self::{} {{ {} }} if field == \"{}\" => {{",
                variant.variant_name, pattern, target_field.name
            ));
            lines.push(format!(
                "                validate_a64_rewrite_field(\"{}\", \"{}\", encoded, {})?;",
                variant.key, target_field.name, target_field.width
            ));
            lines.push(format!(
                "                Ok(Self::{} {{ {} }})",
                variant.variant_name,
                result_fields.join(", ")
            ));
            lines.push("            }".to_string());
        }
    }
    Ok(())
}

fn render_tables(specs: &[InstructionSpec], lines: &mut Vec<String>) -> Result<()> {
    let mut all_entries = Vec::new();

    for spec in specs {
        for variant in &spec.variants {
            let key = format!("{}.{}", variant.section_id, variant.encoding_name);
            let array_name = format!("FIELDS_{}", rust_ident(&key));
            let operand_array_name = format!("OPERANDS_{}", rust_ident(&key));

            lines.push("#[allow(dead_code)]".to_string());
            lines.push(format!(
                "pub const {array_name}: &[GeneratedFieldSpec] = &["
            ));
            for field in &variant.fields {
                lines.push(format!(
                    "    GeneratedFieldSpec {{ name: \"{}\", hi: {}, lo: {}, width: {}, mask: {} }},",
                    field.name, field.hi, field.lo, field.width, field.mask
                ));
            }
            lines.push("];".to_string());
            lines.push("".to_string());

            lines.push("#[allow(dead_code)]".to_string());
            lines.push(format!(
                "pub const {operand_array_name}: &[A64OperandRole] = &["
            ));
            for role in &variant.operand_roles {
                lines.push(format!(
                    "    {},",
                    render_operand_role(role, &variant.fields)?
                ));
            }
            lines.push("];".to_string());
            lines.push("".to_string());

            all_entries.push(format!(
                "GeneratedInsnSpec {{\n    key: \"{}\",\n    mnemonic: \"{}\",\n    heading: \"{}\",\n    title: \"{}\",\n    encoding_label: \"{}\",\n    mask: {},\n    value: {},\n    fields: {},\n    operands: {},\n    asm: {},\n}},",
                key,
                variant.mnemonic,
                variant.heading,
                variant.title,
                variant.encoding_label,
                variant.mask,
                variant.value,
                array_name,
                operand_array_name,
                rust_string(&variant.asm),
            ));
        }
    }

    lines.push("#[allow(dead_code)]".to_string());
    lines.push("pub const GENERATED_A64_SUBSET: &[GeneratedInsnSpec] = &[".to_string());
    for entry in all_entries {
        for line in entry.lines() {
            lines.push(format!("    {line}"));
        }
    }
    lines.push("];".to_string());
    lines.push("".to_string());
    lines.push("#[allow(dead_code)]".to_string());
    lines.push(
        "pub fn generated_a64_subset_match(word: u32) -> Option<&'static GeneratedInsnSpec> {"
            .to_string(),
    );
    lines.push("    let mut index = 0;".to_string());
    lines.push("    while index < GENERATED_A64_SUBSET.len() {".to_string());
    lines.push("        let spec = &GENERATED_A64_SUBSET[index];".to_string());
    lines.push("        if spec.matches(word) {".to_string());
    lines.push("            return Some(spec);".to_string());
    lines.push("        }".to_string());
    lines.push("        index += 1;".to_string());
    lines.push("    }".to_string());
    lines.push("    None".to_string());
    lines.push("}".to_string());
    lines.push("".to_string());
    Ok(())
}

fn render_operand_role(role: &OperandRoleSpec, fields: &[FieldSpec]) -> Result<String> {
    let width = rust_operand_width(&role.width);
    let ret = match role.kind.as_str() {
        "RegRead" => format!(
            "A64OperandRole::RegRead {{ field: \"{}\", width: {} }}",
            role.field, width
        ),
        "RegWrite" => format!(
            "A64OperandRole::RegWrite {{ field: \"{}\", width: {} }}",
            role.field, width
        ),
        "RegReadWrite" => format!(
            "A64OperandRole::RegReadWrite {{ field: \"{}\", width: {} }}",
            role.field, width
        ),
        "ImplicitRegWrite" => {
            let reg = if role.field == "x30" {
                30
            } else {
                role.field.trim_start_matches('x').parse::<u8>()?
            };
            format!(
                "A64OperandRole::ImplicitRegWrite {{ reg: {}, width: {} }}",
                reg, width
            )
        }
        "BranchTarget" => format!(
            "A64OperandRole::BranchTarget {{ field: \"{}\", scale: 2, bits: {} }}",
            role.field,
            branch_role_bits(&role.field, fields)
        ),
        "MemBase" => format!("A64OperandRole::MemBase {{ field: \"{}\" }}", role.field),
        "MemOffset" => format!("A64OperandRole::MemOffset {{ field: \"{}\" }}", role.field),
        "FlagsRead" => "A64OperandRole::FlagsRead".to_string(),
        "FlagsWrite" => "A64OperandRole::FlagsWrite".to_string(),
        "ControlFlow" => "A64OperandRole::ControlFlow".to_string(),
        "Memory" => "A64OperandRole::Memory".to_string(),
        _ => bail!("unsupported operand role: {:?}", role),
    };
    Ok(ret)
}

fn branch_target_roles(variant: &VariantSpec) -> impl Iterator<Item = &OperandRoleSpec> {
    variant
        .operand_roles
        .iter()
        .filter(|role| role.kind == "BranchTarget")
}

fn field_by_name<'a>(fields: &'a [RenderField], name: &str) -> Result<&'a RenderField> {
    fields
        .iter()
        .find(|field| field.name == name)
        .ok_or_else(|| {
            anyhow::anyhow!("missing generated field metadata for branch target field `{name}`")
        })
}

fn branch_role_bits(field_name: &str, fields: &[FieldSpec]) -> u8 {
    fields
        .iter()
        .find(|field| field.name == field_name)
        .map(|field| field.width)
        .unwrap_or(0)
}

fn field_raw_expr(field: &RenderField) -> String {
    match field.rust_type.as_str() {
        "A64Imm" => format!("{}.raw()", field.rust_name),
        "A64Reg" => format!("{}.enc() as u32", field.rust_name),
        _ => format!("*{} as u32", field.rust_name),
    }
}

fn memory_group(variant: &VariantSpec) -> Option<MemGroup> {
    if !variant
        .operand_roles
        .iter()
        .any(|role| role.kind == "Memory")
    {
        return None;
    }
    let base_field = variant
        .operand_roles
        .iter()
        .find(|role| role.kind == "MemBase")?
        .field
        .clone();
    let offset_field = variant
        .operand_roles
        .iter()
        .find(|role| role.kind == "MemOffset")?
        .field
        .clone();
    let base_spec = variant
        .fields
        .iter()
        .find(|field| field.name == base_field)?;
    let offset_spec = variant
        .fields
        .iter()
        .find(|field| field.name == offset_field)?;
    let base_width = register_width(variant, &base_field);
    let base_reg31 = register_31_mode(variant, &base_field);
    let base_raw = format!("((word & {}) >> {}) as u8", base_spec.mask, base_spec.shift);
    let offset_raw = format!(
        "((word & {}) >> {}) as u32",
        offset_spec.mask, offset_spec.shift
    );

    Some(MemGroup {
        base_field,
        offset_field,
        base_shift: base_spec.shift,
        offset_width: offset_spec.width,
        offset_shift: offset_spec.shift,
        mode: memory_mode(&variant.asm),
        offset_decode: render_mem_offset_decode(variant, offset_spec, &offset_raw),
        base_decode: format!("A64Reg::new({base_raw}, {base_width}, {base_reg31})"),
    })
}

fn memory_mode(asm: &str) -> &'static str {
    if asm.contains("]!") {
        "pre_index"
    } else if asm.contains("],") {
        "post_index"
    } else {
        "offset"
    }
}

fn render_mem_offset_decode(variant: &VariantSpec, field: &FieldSpec, raw: &str) -> String {
    let signed = immediate_operand_text(variant, &field.name)
        .map(|text| immediate_is_signed(&text))
        .unwrap_or_else(|| matches!(field.name.as_str(), "imm7" | "imm9"));
    let scale = immediate_scale(variant, &field.name);
    let ctor = match (signed, scale) {
        (true, 0) => "A64Imm::signed",
        (false, 0) => "A64Imm::unsigned",
        (true, _) => "A64Imm::scaled_signed",
        (false, _) => "A64Imm::scaled_unsigned",
    };
    if scale == 0 {
        format!("{ctor}({raw}, {})", field.width)
    } else {
        format!("{ctor}({raw}, {}, {scale})", field.width)
    }
}

fn render_imm_decode(variant: &VariantSpec, field: &FieldSpec, raw: &str) -> String {
    if variant
        .operand_roles
        .iter()
        .find(|role| role.kind == "BranchTarget" && role.field == field.name)
        .is_some()
    {
        return format!("A64Imm::scaled_signed({raw}, {}, 2)", field.width);
    }

    let signed = immediate_operand_text(variant, &field.name)
        .map(|text| immediate_is_signed(&text))
        .unwrap_or(false);
    if signed {
        format!("A64Imm::signed({raw}, {})", field.width)
    } else {
        format!("A64Imm::unsigned({raw}, {})", field.width)
    }
}

fn immediate_operand_text(variant: &VariantSpec, field: &str) -> Option<String> {
    let encoded_in_field = format!("\"{field}\" field");
    variant
        .asm_operands
        .iter()
        .find(|operand| operand.hover.contains(&encoded_in_field))
        .map(|operand| format!("{} {}", operand.text, operand.hover))
}

fn immediate_is_signed(text: &str) -> bool {
    let lower = text.to_ascii_lowercase();
    !lower.contains("unsigned") && (lower.contains("signed") || lower.contains("<simm>"))
}

fn immediate_scale(variant: &VariantSpec, field: &str) -> u8 {
    let Some(text) = immediate_operand_text(variant, field) else {
        return 0;
    };
    if text.contains("/16") {
        4
    } else if text.contains("/8") {
        3
    } else if text.contains("/4") {
        2
    } else if text.contains("/2") {
        1
    } else {
        0
    }
}

fn is_register_field(field: &FieldSpec) -> bool {
    field.width == 5
        && matches!(
            field.name.as_str(),
            "Rd" | "Rn" | "Rm" | "Rt" | "Rt2" | "Ra" | "Rs"
        )
}

fn register_width(variant: &VariantSpec, field: &str) -> &'static str {
    variant
        .operand_roles
        .iter()
        .find(|role| {
            matches!(role.kind.as_str(), "RegRead" | "RegWrite" | "RegReadWrite")
                && role.field == field
        })
        .map(|role| rust_operand_width(&role.width))
        .unwrap_or("A64RegWidth::Unknown")
}

fn register_31_mode(variant: &VariantSpec, field: &str) -> &'static str {
    let encoded_in_field = format!("\"{field}\" field");
    for operand in &variant.asm_operands {
        if !operand.hover.contains(&encoded_in_field) {
            continue;
        }
        if operand.text.contains("|SP")
            || operand.text.contains("|WSP")
            || operand.link.contains("SP_option")
            || operand.hover.to_ascii_lowercase().contains("stack pointer")
        {
            return "A64Reg31Mode::Sp";
        }
        if operand.link.contains("OrXZR") {
            return "A64Reg31Mode::Xzr";
        }
    }

    "A64Reg31Mode::Xzr"
}

fn rust_operand_width(width: &str) -> &'static str {
    match width {
        "W32" => "A64RegWidth::W32",
        "X64" => "A64RegWidth::X64",
        _ => "A64RegWidth::Unknown",
    }
}

fn rust_field_type(width: u8) -> &'static str {
    if width <= 8 {
        "u8"
    } else if width <= 16 {
        "u16"
    } else {
        "u32"
    }
}

fn rust_ident(text: &str) -> String {
    let mut chars = String::new();
    for ch in text.chars() {
        if ch.is_ascii_alphanumeric() {
            chars.push(ch.to_ascii_uppercase());
        } else {
            chars.push('_');
        }
    }

    let mut ident = chars.trim_matches('_').to_string();
    while ident.contains("__") {
        ident = ident.replace("__", "_");
    }
    if ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        ident = format!("V_{ident}");
    }
    if ident.is_empty() {
        "UNNAMED".to_string()
    } else {
        ident
    }
}

fn rust_variant_ident(text: &str) -> String {
    let ident = rust_ident(text);
    let mut variant = String::new();
    for part in ident.split('_').filter(|part| !part.is_empty()) {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            variant.push(first);
            variant.push_str(&chars.as_str().to_ascii_lowercase());
        }
    }
    if variant.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        variant = format!("V{variant}");
    }
    if variant.is_empty() {
        "Unnamed".to_string()
    } else {
        variant
    }
}

fn rust_field_ident(text: &str) -> String {
    let mut chars = String::new();
    let mut prev_lower_or_digit = false;

    for ch in text.chars() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() && prev_lower_or_digit {
                chars.push('_');
            }
            chars.push(ch.to_ascii_lowercase());
            prev_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        } else {
            chars.push('_');
            prev_lower_or_digit = false;
        }
    }

    let mut ident = chars.trim_matches('_').to_string();
    while ident.contains("__") {
        ident = ident.replace("__", "_");
    }
    if ident.is_empty() {
        ident = "field".to_string();
    }
    if ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        ident = format!("field_{ident}");
    }
    if is_rust_keyword(&ident) {
        ident = format!("{ident}_field");
    }
    ident
}

fn is_rust_keyword(ident: &str) -> bool {
    matches!(
        ident,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
    )
}

fn rust_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rust_variant_ident_matches_python_generator_shape() {
        assert_eq!(
            rust_variant_ident("CBNZ.CBNZ_64_compbranch"),
            "CbnzCbnz64Compbranch"
        );
    }

    #[test]
    fn rust_field_ident_handles_arm_field_names() {
        assert_eq!(rust_field_ident("Rn"), "rn");
        assert_eq!(rust_field_ident("imm12"), "imm12");
        assert_eq!(rust_field_ident("class"), "class");
    }
}
