use crate::model::{FieldSpec, InstructionSpec, OperandRoleSpec, VariantSpec};
use anyhow::{bail, Result};

#[derive(Clone, Debug)]
struct RenderField {
    name: String,
    width: u8,
    shift: u8,
    mask: String,
    rust_name: String,
    rust_type: &'static str,
}

#[derive(Clone, Debug)]
struct RenderVariant<'a> {
    spec: &'a VariantSpec,
    key: String,
    variant_name: String,
    fields: Vec<RenderField>,
    operand_array_name: String,
}

pub fn render_rust(specs: &[InstructionSpec]) -> Result<String> {
    let mut lines = vec![
        "// Generated by specgen from Arm ISA XML.".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug)]".to_string(),
        "pub struct GeneratedFieldSpec {".to_string(),
        "    pub name: &'static str,".to_string(),
        "    pub hi: u8,".to_string(),
        "    pub lo: u8,".to_string(),
        "    pub width: u8,".to_string(),
        "    pub mask: u32,".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "impl GeneratedFieldSpec {".to_string(),
        "    pub const fn shift(&self) -> u8 {".to_string(),
        "        self.lo".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn extract(&self, word: u32) -> u32 {".to_string(),
        "        (word & self.mask) >> self.lo".to_string(),
        "    }".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64RegWidth {".to_string(),
        "    W32,".to_string(),
        "    X64,".to_string(),
        "    Unknown,".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64OperandRole {".to_string(),
        "    RegRead { field: &'static str, width: A64RegWidth },".to_string(),
        "    RegWrite { field: &'static str, width: A64RegWidth },".to_string(),
        "    RegReadWrite { field: &'static str, width: A64RegWidth },".to_string(),
        "    ImplicitRegWrite { reg: u8, width: A64RegWidth },".to_string(),
        "    BranchTarget { field: &'static str, scale: u8, bits: u8 },".to_string(),
        "    MemBase { field: &'static str },".to_string(),
        "    MemOffset { field: &'static str },".to_string(),
        "    FlagsRead,".to_string(),
        "    FlagsWrite,".to_string(),
        "    ControlFlow,".to_string(),
        "    Memory,".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug)]".to_string(),
        "pub struct GeneratedInsnSpec {".to_string(),
        "    pub key: &'static str,".to_string(),
        "    pub mnemonic: &'static str,".to_string(),
        "    pub heading: &'static str,".to_string(),
        "    pub title: &'static str,".to_string(),
        "    pub encoding_label: &'static str,".to_string(),
        "    pub mask: u32,".to_string(),
        "    pub value: u32,".to_string(),
        "    pub fields: &'static [GeneratedFieldSpec],".to_string(),
        "    pub operands: &'static [A64OperandRole],".to_string(),
        "    pub asm: &'static str,".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "impl GeneratedInsnSpec {".to_string(),
        "    pub const fn matches(&self, word: u32) -> bool {".to_string(),
        "        (word & self.mask) == self.value".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn field(&self, name: &str) -> Option<&'static GeneratedFieldSpec> {".to_string(),
        "        let mut index = 0;".to_string(),
        "        while index < self.fields.len() {".to_string(),
        "            let field = &self.fields[index];".to_string(),
        "            if field.name == name {".to_string(),
        "                return Some(field);".to_string(),
        "            }".to_string(),
        "            index += 1;".to_string(),
        "        }".to_string(),
        "        None".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn extract_field(&self, word: u32, name: &str) -> Option<u32> {".to_string(),
        "        self.field(name).map(|field| field.extract(word))".to_string(),
        "    }".to_string(),
        "}".to_string(),
        "".to_string(),
    ];

    lines.extend(render_a64_insn(specs)?);
    render_tables(specs, &mut lines)?;
    Ok(lines.join("\n"))
}

fn render_a64_insn(specs: &[InstructionSpec]) -> Result<Vec<String>> {
    let variants = render_variants(specs);
    let mut lines = vec![
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64Insn {".to_string(),
    ];

    for variant in &variants {
        lines.push(format!("    {} {{", variant.variant_name));
        for field in &variant.fields {
            lines.push(format!("        {}: {},", field.rust_name, field.rust_type));
        }
        lines.push("    },".to_string());
    }
    lines.push("}".to_string());
    lines.push("".to_string());

    lines.extend([
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64EncodeError {".to_string(),
        "    FieldOutOfRange {".to_string(),
        "        insn: &'static str,".to_string(),
        "        field: &'static str,".to_string(),
        "        value: u32,".to_string(),
        "        width: u8,".to_string(),
        "    },".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]".to_string(),
        "pub enum A64RewriteError {".to_string(),
        "    UnsupportedField {".to_string(),
        "        insn: &'static str,".to_string(),
        "        field: &'static str,".to_string(),
        "    },".to_string(),
        "    FieldOutOfRange {".to_string(),
        "        insn: &'static str,".to_string(),
        "        field: &'static str,".to_string(),
        "        value: u32,".to_string(),
        "        width: u8,".to_string(),
        "    },".to_string(),
        "}".to_string(),
        "".to_string(),
        "fn encode_a64_field(".to_string(),
        "    insn: &'static str,".to_string(),
        "    field: &'static str,".to_string(),
        "    value: u32,".to_string(),
        "    width: u8,".to_string(),
        "    shift: u8,".to_string(),
        ") -> Result<u32, A64EncodeError> {".to_string(),
        "    if width < 32 && value >= (1_u32 << width) {".to_string(),
        "        return Err(A64EncodeError::FieldOutOfRange {".to_string(),
        "            insn,".to_string(),
        "            field,".to_string(),
        "            value,".to_string(),
        "            width,".to_string(),
        "        });".to_string(),
        "    }".to_string(),
        "    Ok(value << shift)".to_string(),
        "}".to_string(),
        "".to_string(),
        "fn validate_a64_rewrite_field(".to_string(),
        "    insn: &'static str,".to_string(),
        "    field: &'static str,".to_string(),
        "    value: u32,".to_string(),
        "    width: u8,".to_string(),
        ") -> Result<(), A64RewriteError> {".to_string(),
        "    if width < 32 && value >= (1_u32 << width) {".to_string(),
        "        return Err(A64RewriteError::FieldOutOfRange {".to_string(),
        "            insn,".to_string(),
        "            field,".to_string(),
        "            value,".to_string(),
        "            width,".to_string(),
        "        });".to_string(),
        "    }".to_string(),
        "    Ok(())".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "impl A64Insn {".to_string(),
        "    pub const fn key(&self) -> &'static str {".to_string(),
        "        match self {".to_string(),
    ]);
    for variant in &variants {
        lines.push(format!(
            "            Self::{} {{ .. }} => \"{}\",",
            variant.variant_name, variant.key
        ));
    }

    lines.extend([
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn mnemonic(&self) -> &'static str {".to_string(),
        "        match self {".to_string(),
    ]);
    for variant in &variants {
        lines.push(format!(
            "            Self::{} {{ .. }} => \"{}\",",
            variant.variant_name, variant.spec.mnemonic
        ));
    }

    lines.extend([
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn asm_template(&self) -> &'static str {".to_string(),
        "        match self {".to_string(),
    ]);
    for variant in &variants {
        lines.push(format!(
            "            Self::{} {{ .. }} => {},",
            variant.variant_name,
            rust_string(&variant.spec.asm)
        ));
    }

    lines.extend([
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn decode(word: u32) -> Option<Self> {".to_string(),
        "        decode_a64_insn(word)".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn encode(self) -> Result<u32, A64EncodeError> {".to_string(),
        "        match self {".to_string(),
    ]);
    render_encode_arms(&variants, &mut lines);

    lines.extend([
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn branch_target_imm(&self, field: &'static str) -> Option<u32> {".to_string(),
        "        match self {".to_string(),
    ]);
    render_branch_getter_arms(&variants, &mut lines)?;

    lines.extend([
        "            _ => None,".to_string(),
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub fn set_branch_target_imm(".to_string(),
        "        self,".to_string(),
        "        field: &'static str,".to_string(),
        "        encoded: u32,".to_string(),
        "    ) -> Result<Self, A64RewriteError> {".to_string(),
        "        let insn_key = self.key();".to_string(),
        "        match self {".to_string(),
    ]);
    render_branch_setter_arms(&variants, &mut lines)?;

    lines.extend([
        "            _ => Err(A64RewriteError::UnsupportedField {".to_string(),
        "                insn: insn_key,".to_string(),
        "                field,".to_string(),
        "            }),".to_string(),
        "        }".to_string(),
        "    }".to_string(),
        "".to_string(),
        "    pub const fn operand_roles(&self) -> &'static [A64OperandRole] {".to_string(),
        "        match self {".to_string(),
    ]);
    for variant in &variants {
        lines.push(format!(
            "            Self::{} {{ .. }} => {},",
            variant.variant_name, variant.operand_array_name
        ));
    }

    lines.extend([
        "        }".to_string(),
        "    }".to_string(),
        "}".to_string(),
        "".to_string(),
        "#[allow(dead_code)]".to_string(),
        "pub fn decode_a64_insn(word: u32) -> Option<A64Insn> {".to_string(),
    ]);
    render_decode_arms(&variants, &mut lines);

    lines.extend(["    None".to_string(), "}".to_string(), "".to_string()]);
    Ok(lines)
}

fn render_variants(specs: &[InstructionSpec]) -> Vec<RenderVariant<'_>> {
    specs
        .iter()
        .flat_map(|spec| &spec.variants)
        .map(|variant| {
            let key = format!("{}.{}", variant.section_id, variant.encoding_name);
            let fields = variant
                .fields
                .iter()
                .filter(|field| field.variable)
                .map(render_field)
                .collect();
            RenderVariant {
                spec: variant,
                variant_name: rust_variant_ident(&key),
                operand_array_name: format!("OPERANDS_{}", rust_ident(&key)),
                key,
                fields,
            }
        })
        .collect()
}

fn render_field(field: &FieldSpec) -> RenderField {
    RenderField {
        name: field.name.clone(),
        width: field.width,
        shift: field.shift,
        mask: field.mask.clone(),
        rust_name: rust_field_ident(&field.name),
        rust_type: rust_field_type(field.width),
    }
}

fn render_encode_arms(variants: &[RenderVariant<'_>], lines: &mut Vec<String>) {
    for variant in variants {
        if variant.fields.is_empty() {
            lines.push(format!(
                "            Self::{} {{ }} => {{",
                variant.variant_name
            ));
            lines.push(format!(
                "                let word = {};",
                variant.spec.value
            ));
        } else {
            let field_list = variant
                .fields
                .iter()
                .map(|field| field.rust_name.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            lines.push(format!(
                "            Self::{} {{ {} }} => {{",
                variant.variant_name, field_list
            ));
            lines.push(format!(
                "                let mut word = {};",
                variant.spec.value
            ));
        }

        for field in &variant.fields {
            lines.push(format!(
                "                word |= encode_a64_field(\"{}\", \"{}\", {} as u32, {}, {})?;",
                variant.key, field.name, field.rust_name, field.width, field.shift
            ));
        }
        lines.push("                Ok(word)".to_string());
        lines.push("            }".to_string());
    }
}

fn render_decode_arms(variants: &[RenderVariant<'_>], lines: &mut Vec<String>) {
    for variant in variants {
        lines.push(format!(
            "    if (word & {}) == {} {{",
            variant.spec.mask, variant.spec.value
        ));
        if variant.fields.is_empty() {
            lines.push(format!(
                "        return Some(A64Insn::{} {{ }});",
                variant.variant_name
            ));
        } else {
            lines.push(format!(
                "        return Some(A64Insn::{} {{",
                variant.variant_name
            ));
            for field in &variant.fields {
                lines.push(format!(
                    "            {}: ((word & {}) >> {}) as {},",
                    field.rust_name, field.mask, field.shift, field.rust_type
                ));
            }
            lines.push("        });".to_string());
        }
        lines.push("    }".to_string());
    }
}

fn render_branch_getter_arms(
    variants: &[RenderVariant<'_>],
    lines: &mut Vec<String>,
) -> Result<()> {
    for variant in variants {
        for role in branch_target_roles(variant.spec) {
            let target_field = field_by_name(&variant.fields, &role.field)?;
            lines.push(format!(
                "            Self::{} {{ {}, .. }} if field == \"{}\" => Some(*{} as u32),",
                variant.variant_name,
                target_field.rust_name,
                target_field.name,
                target_field.rust_name
            ));
        }
    }
    Ok(())
}

fn render_branch_setter_arms(
    variants: &[RenderVariant<'_>],
    lines: &mut Vec<String>,
) -> Result<()> {
    for variant in variants {
        for role in branch_target_roles(variant.spec) {
            let target_field = field_by_name(&variant.fields, &role.field)?;
            let mut pattern_fields = Vec::new();
            let mut result_fields = Vec::new();

            for field in &variant.fields {
                if field.name == target_field.name {
                    result_fields.push(format!(
                        "{}: encoded as {}",
                        field.rust_name, field.rust_type
                    ));
                } else {
                    pattern_fields.push(field.rust_name.clone());
                    result_fields.push(field.rust_name.clone());
                }
            }

            let pattern = if pattern_fields.is_empty() {
                "..".to_string()
            } else {
                format!("{}, ..", pattern_fields.join(", "))
            };
            lines.push(format!(
                "            Self::{} {{ {} }} if field == \"{}\" => {{",
                variant.variant_name, pattern, target_field.name
            ));
            lines.push(format!(
                "                validate_a64_rewrite_field(\"{}\", \"{}\", encoded, {})?;",
                variant.key, target_field.name, target_field.width
            ));
            lines.push(format!(
                "                Ok(Self::{} {{ {} }})",
                variant.variant_name,
                result_fields.join(", ")
            ));
            lines.push("            }".to_string());
        }
    }
    Ok(())
}

fn render_tables(specs: &[InstructionSpec], lines: &mut Vec<String>) -> Result<()> {
    let mut all_entries = Vec::new();

    for spec in specs {
        for variant in &spec.variants {
            let key = format!("{}.{}", variant.section_id, variant.encoding_name);
            let array_name = format!("FIELDS_{}", rust_ident(&key));
            let operand_array_name = format!("OPERANDS_{}", rust_ident(&key));

            lines.push("#[allow(dead_code)]".to_string());
            lines.push(format!(
                "pub const {array_name}: &[GeneratedFieldSpec] = &["
            ));
            for field in &variant.fields {
                lines.push(format!(
                    "    GeneratedFieldSpec {{ name: \"{}\", hi: {}, lo: {}, width: {}, mask: {} }},",
                    field.name, field.hi, field.lo, field.width, field.mask
                ));
            }
            lines.push("];".to_string());
            lines.push("".to_string());

            lines.push("#[allow(dead_code)]".to_string());
            lines.push(format!(
                "pub const {operand_array_name}: &[A64OperandRole] = &["
            ));
            for role in &variant.operand_roles {
                lines.push(format!(
                    "    {},",
                    render_operand_role(role, &variant.fields)?
                ));
            }
            lines.push("];".to_string());
            lines.push("".to_string());

            all_entries.push(format!(
                "GeneratedInsnSpec {{\n    key: \"{}\",\n    mnemonic: \"{}\",\n    heading: \"{}\",\n    title: \"{}\",\n    encoding_label: \"{}\",\n    mask: {},\n    value: {},\n    fields: {},\n    operands: {},\n    asm: {},\n}},",
                key,
                variant.mnemonic,
                variant.heading,
                variant.title,
                variant.encoding_label,
                variant.mask,
                variant.value,
                array_name,
                operand_array_name,
                rust_string(&variant.asm),
            ));
        }
    }

    lines.push("#[allow(dead_code)]".to_string());
    lines.push("pub const GENERATED_A64_SUBSET: &[GeneratedInsnSpec] = &[".to_string());
    for entry in all_entries {
        for line in entry.lines() {
            lines.push(format!("    {line}"));
        }
    }
    lines.push("];".to_string());
    lines.push("".to_string());
    lines.push("#[allow(dead_code)]".to_string());
    lines.push(
        "pub fn generated_a64_subset_match(word: u32) -> Option<&'static GeneratedInsnSpec> {"
            .to_string(),
    );
    lines.push("    let mut index = 0;".to_string());
    lines.push("    while index < GENERATED_A64_SUBSET.len() {".to_string());
    lines.push("        let spec = &GENERATED_A64_SUBSET[index];".to_string());
    lines.push("        if spec.matches(word) {".to_string());
    lines.push("            return Some(spec);".to_string());
    lines.push("        }".to_string());
    lines.push("        index += 1;".to_string());
    lines.push("    }".to_string());
    lines.push("    None".to_string());
    lines.push("}".to_string());
    lines.push("".to_string());
    Ok(())
}

fn render_operand_role(role: &OperandRoleSpec, fields: &[FieldSpec]) -> Result<String> {
    let width = rust_operand_width(&role.width);
    let ret = match role.kind.as_str() {
        "RegRead" => format!(
            "A64OperandRole::RegRead {{ field: \"{}\", width: {} }}",
            role.field, width
        ),
        "RegWrite" => format!(
            "A64OperandRole::RegWrite {{ field: \"{}\", width: {} }}",
            role.field, width
        ),
        "RegReadWrite" => format!(
            "A64OperandRole::RegReadWrite {{ field: \"{}\", width: {} }}",
            role.field, width
        ),
        "ImplicitRegWrite" => {
            let reg = if role.field == "x30" {
                30
            } else {
                role.field.trim_start_matches('x').parse::<u8>()?
            };
            format!(
                "A64OperandRole::ImplicitRegWrite {{ reg: {}, width: {} }}",
                reg, width
            )
        }
        "BranchTarget" => format!(
            "A64OperandRole::BranchTarget {{ field: \"{}\", scale: 2, bits: {} }}",
            role.field,
            branch_role_bits(&role.field, fields)
        ),
        "MemBase" => format!("A64OperandRole::MemBase {{ field: \"{}\" }}", role.field),
        "MemOffset" => format!("A64OperandRole::MemOffset {{ field: \"{}\" }}", role.field),
        "FlagsRead" => "A64OperandRole::FlagsRead".to_string(),
        "FlagsWrite" => "A64OperandRole::FlagsWrite".to_string(),
        "ControlFlow" => "A64OperandRole::ControlFlow".to_string(),
        "Memory" => "A64OperandRole::Memory".to_string(),
        _ => bail!("unsupported operand role: {:?}", role),
    };
    Ok(ret)
}

fn branch_target_roles(variant: &VariantSpec) -> impl Iterator<Item = &OperandRoleSpec> {
    variant
        .operand_roles
        .iter()
        .filter(|role| role.kind == "BranchTarget")
}

fn field_by_name<'a>(fields: &'a [RenderField], name: &str) -> Result<&'a RenderField> {
    fields
        .iter()
        .find(|field| field.name == name)
        .ok_or_else(|| {
            anyhow::anyhow!("missing generated field metadata for branch target field `{name}`")
        })
}

fn branch_role_bits(field_name: &str, fields: &[FieldSpec]) -> u8 {
    fields
        .iter()
        .find(|field| field.name == field_name)
        .map(|field| field.width)
        .unwrap_or(0)
}

fn rust_operand_width(width: &str) -> &'static str {
    match width {
        "W32" => "A64RegWidth::W32",
        "X64" => "A64RegWidth::X64",
        _ => "A64RegWidth::Unknown",
    }
}

fn rust_field_type(width: u8) -> &'static str {
    if width <= 8 {
        "u8"
    } else if width <= 16 {
        "u16"
    } else {
        "u32"
    }
}

fn rust_ident(text: &str) -> String {
    let mut chars = String::new();
    for ch in text.chars() {
        if ch.is_ascii_alphanumeric() {
            chars.push(ch.to_ascii_uppercase());
        } else {
            chars.push('_');
        }
    }

    let mut ident = chars.trim_matches('_').to_string();
    while ident.contains("__") {
        ident = ident.replace("__", "_");
    }
    if ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        ident = format!("V_{ident}");
    }
    if ident.is_empty() {
        "UNNAMED".to_string()
    } else {
        ident
    }
}

fn rust_variant_ident(text: &str) -> String {
    let ident = rust_ident(text);
    let mut variant = String::new();
    for part in ident.split('_').filter(|part| !part.is_empty()) {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            variant.push(first);
            variant.push_str(&chars.as_str().to_ascii_lowercase());
        }
    }
    if variant.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        variant = format!("V{variant}");
    }
    if variant.is_empty() {
        "Unnamed".to_string()
    } else {
        variant
    }
}

fn rust_field_ident(text: &str) -> String {
    let mut chars = String::new();
    let mut prev_lower_or_digit = false;

    for ch in text.chars() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() && prev_lower_or_digit {
                chars.push('_');
            }
            chars.push(ch.to_ascii_lowercase());
            prev_lower_or_digit = ch.is_ascii_lowercase() || ch.is_ascii_digit();
        } else {
            chars.push('_');
            prev_lower_or_digit = false;
        }
    }

    let mut ident = chars.trim_matches('_').to_string();
    while ident.contains("__") {
        ident = ident.replace("__", "_");
    }
    if ident.is_empty() {
        ident = "field".to_string();
    }
    if ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        ident = format!("field_{ident}");
    }
    if is_rust_keyword(&ident) {
        ident = format!("{ident}_field");
    }
    ident
}

fn is_rust_keyword(ident: &str) -> bool {
    matches!(
        ident,
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
    )
}

fn rust_string(value: &str) -> String {
    serde_json::to_string(value).expect("string serialization cannot fail")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rust_variant_ident_matches_python_generator_shape() {
        assert_eq!(
            rust_variant_ident("CBNZ.CBNZ_64_compbranch"),
            "CbnzCbnz64Compbranch"
        );
    }

    #[test]
    fn rust_field_ident_handles_arm_field_names() {
        assert_eq!(rust_field_ident("Rn"), "rn");
        assert_eq!(rust_field_ident("imm12"), "imm12");
        assert_eq!(rust_field_ident("class"), "class");
    }
}
