mod frame;
mod regs;
mod wrapper;

pub use frame::{
    ibtc_slot_index, pt_regs_x_slot_offset, reg_virt_stack_backed_slot_offset,
    EXTRA_PARAMS_BYTES, EXTRA_PARAMS_WORDS, EXTRA_PARAM_IBTC_TABLE_INDEX,
    EXTRA_PARAM_IBTC_TABLE_OFFSET, IBTC_BITS, IBTC_INDEX_LSB, IBTC_RECORD_BYTES,
    IBTC_RECORD_HOST_OFFSET, IBTC_RECORD_PC_OFFSET, IBTC_SLOTS, IBTC_SLOT_BYTES, IBTC_SLOT_SHIFT,
    IBTC_TABLE_BYTES, KJIT_BACKEDGE_BUDGET, RUNTIME_FRAME_BUDGET_OFFSET,
    RUNTIME_FRAME_ENTRY_ADDR_OFFSET, RUNTIME_FRAME_IBTC_OFFSET, RUNTIME_FRAME_PT_REGS_PTR_OFFSET,
    RUNTIME_FRAME_SIZE_BYTES,
};
pub use regs::{
    reg_virt_scratch_gpr, DISPATCH_KEY_REG, DISPATCH_SLOT_REG, DISPATCH_TARGET_REG, RetStatus, ABI_ENTRY_ARG_REG, ABI_EXTRA_PARAMS_ARG_REG, ABI_LINK_REG,
    ABI_PT_REGS_ARG_REG, PAN_WINDOW_RANGE_TOP_BIT, REG_VIRT_SCRATCH_GPR_END, REG_VIRT_SCRATCH_GPR_LIMIT,
    REG_VIRT_SCRATCH_GPR_START, REG_VIRT_STABLE_MAPPED_SP_PHYS_REG,
    REG_VIRT_STABLE_MAPPED_X29_PHYS_REG, REG_VIRT_STABLE_MAPPED_X29_REG,
    REG_VIRT_STACK_BACKED_REG_END, REG_VIRT_STACK_BACKED_REG_START, RET_PARAM0_REG, RET_PARAM1_REG,
    RET_STATUS_REG, UNSUPPORTED_WORD_UNREADABLE, USER_VA_BITS,
};
pub use wrapper::{
    append_epilogue, append_prologue, copy_epilogue, copy_prologue, dispatch_template_matches,
    ABI_INSN_SIZE, DISPATCH_TEMPLATE_LEN, DISPATCH_TEMPLATE_MISS_BRANCHES, EPILOGUE_LEN_BYTES,
    EPILOGUE_OFFSET, KJIT_DISPATCH_TEMPLATE, KJIT_EPILOGUE, KJIT_PROLOGUE, PROLOGUE_LEN_BYTES,
};
